name: Bug Report on DocuGen 
description: File a bug report
title: "AVOID generic bug titles, be SPECIFIC please!"
labels: ["bug"]
assignees:
  - mohammed-ibenayad
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The system clears all items in the shopping cart while trying to update a product quantity with an invalid number (negative or floating-point number).
      value:
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - ShowStopper 
        - Major
        - Minor
        - NiceToHave
  - type: textarea
    id: howto_reproduce
    attributes:
      label: Steps to reproduce the bug
      description: Steps to reproduce the bug.
      placeholder: (1) Add more than one product to the shopping cart. - (2) View the shopping cart items. - (3) Update the quantity of one item with a negative or floating-point number. - (4) Click on the update button
      value:
    validations:
      required: true
  - type: textarea
    id: actual_results
    attributes:
      label: Actual results
      description: Concise description of the system results after going through the steps.
      placeholder: The system deletes all items in the shopping cart and prompt the user to a screen showing a message that the shopping cart is empty.
      value:
    validations:
      required: true
  - type: textarea
    id: test_data
    attributes:
      label: Test Data
      description: It can be precisely the data you have entered, only what you think is relevant to the bug.
      placeholder: username=test
      value:
    validations:
      required: false
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Concise description of what you expected to happen by refering to requirements.
      placeholder: The system should display an error stating that the product quantity should be an integer.
      value:
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Feature
      description: What feature of the software you foud the bug?
      options:
        - Installation and setup
        - Generating documents
        - Working with templates
        - Working with placeholders
        - Working with tables
    validations:
      required: true     
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
